title: Oleg Bukatchuk
url: "https://bukatchuk.com"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/olegbukatchuk"
footer_text: "Design by Oleg Bukatchuk"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Blog"
   link: "https://bukatch.uk"
 - name: "Contact"
   link: "contact"
