# Site settings
name: Oleg Bukatchuk
title: Oleg Bukatchuk | Site Reability Engineer
description: Design-minded software engineer focused on building beautiful interfaces and experiences
url: https://bukatchuk.com/
baseurl: ''
email: oleg@bukatchuk.com
cover: https://bukatchuk.com/img/og.png
logo: https://bukatchuk.com/img/emojis/technologist.png
resume: https://bukatchuk.com/resume.pdf
social:
  - title: email
    url: mailto:oleg@bukatchuk.com
  - title: twitter
    url: https://twitter.com/olegbukatchuk
  - title: instagram
    url: https://instagram.com/olegbukatchuk
  - title: vk
    url: http://codepen.io/olegbukatchuk
  - title: github
    url: https://github.com/olegbukatchuk
  - title: linkedin
    url: https://www.linkedin.com/in/olegbukatchuk

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
